In [58]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

ModuleNotFoundError: No module named 'matplotlib'

In [25]:
# Read CSV Files
plays_df = pd.read_csv("datafiles/plays.csv")
players_df = pd.read_csv("datafiles/players.csv")
week1_df = pd.read_csv("datafiles/week1.csv")
week2_df = pd.read_csv("datafiles/week2.csv")
week3_df = pd.read_csv("datafiles/week3.csv")

In [26]:
plays_df.head(10)

,gameId,playId,playDescription,quarter,down,yardsToGo,possessionTeam,playType,yardlineSide,yardlineNumber,...,preSnapHomeScore,gameClock,absoluteYardlineNumber,penaltyCodes,penaltyJerseyNumbers,passResult,offensePlayResult,playResult,epa,isDefensivePI
0,2018090600,75,(15:00) M.Ryan pass short right to J.Jones pus...,1,1,15,ATL,play_type_pass,ATL,20,...,0.0,15:00:00,90.0,NaN,NaN,C,10,10,0.261827,False
1,2018090600,146,(13:10) M.Ryan pass incomplete short right to ...,1,1,10,ATL,play_type_pass,PHI,39,...,0.0,13:10:00,49.0,NaN,NaN,I,0,0,-0.372360,False
2,2018090600,168,(13:05) (Shotgun) M.Ryan pass incomplete short...,1,2,10,ATL,play_type_pass,PHI,39,...,0.0,13:05:00,49.0,NaN,NaN,I,0,0,-0.702779,False
3,2018090600,190,(13:01) (Shotgun) M.Ryan pass deep left to J.J...,1,3,10,ATL,play_type_pass,PHI,39,...,0.0,13:01:00,49.0,NaN,NaN,C,33,33,3.047530,False
4,2018090600,256,(10:59) (Shotgun) M.Ryan pass incomplete short...,1,3,1,ATL,play_type_pass,PHI,1,...,0.0,10:59:00,11.0,NaN,NaN,I,0,0,-0.842272,False
5,2018090600,320,(10:10) (Shotgun) N.Foles pass short left to N...,1,2,8,PHI,play_type_pass,PHI,4,...,0.0,10:10:00,14.0,NaN,NaN,C,4,4,-0.344096,False
6,2018090600,344,(9:24) (Shotgun) N.Foles pass incomplete short...,1,3,4,PHI,play_type_pass,PHI,8,...,0.0,09:24:00,18.0,NaN,NaN,I,0,0,-1.192208,False
7,2018090600,402,(9:08) M.Ryan pass incomplete deep left to M.S...,1,1,10,ATL,play_type_pass,PHI,44,...,0.0,09:08:00,54.0,NaN,NaN,I,0,0,-0.429863,False
8,2018090600,492,(7:01) M.Ryan pass short left to T.Coleman pus...,1,2,13,ATL,play_type_pass,PHI,36,...,0.0,07:01:00,46.0,NaN,NaN,C,26,26,1.879804,False
9,2018090600,521,(6:19) M.Ryan pass short left to A.Hooper to P...,1,1,10,ATL,play_type_pass,PHI,10,...,0.0,06:19:00,20.0,NaN,NaN,C,3,3,0.045665,False

In [27]:
plays_df.tail(10)

,gameId,playId,playDescription,quarter,down,yardsToGo,possessionTeam,playType,yardlineSide,yardlineNumber,...,preSnapHomeScore,gameClock,absoluteYardlineNumber,penaltyCodes,penaltyJerseyNumbers,passResult,offensePlayResult,playResult,epa,isDefensivePI
19229,2018123013,4238,(1:55) (Shotgun) G.Smith sacked at LAC 18 for ...,4,3,15,LAC,play_type_unknown,LAC,26,...,NaN,NaN,NaN,DH,DEN 41,S,-8,5,0.887859,False
19230,2018123015,2742,(6:13) (Shotgun) R.Wilson sacked at SEA 3 for ...,3,3,6,SEA,play_type_unknown,SEA,6,...,NaN,NaN,NaN,DH,ARI 43,S,-3,5,1.795895,False
19231,2018123014,1212,(15:00) (Shotgun) J.Goff pass short left to J....,2,2,15,LA,play_type_unknown,LA,44,...,NaN,NaN,NaN,ICT,SF 24,C,13,5,0.840261,False
19232,2018123014,2022,(4:08) (Shotgun) N.Mullens pass incomplete sho...,2,2,9,SF,play_type_unknown,LA,48,...,NaN,NaN,NaN,RPS,LA 26,I,0,15,1.218791,False
19233,2018123014,2170,(2:18) (Shotgun) N.Mullens pass incomplete sho...,2,3,6,SF,play_type_unknown,LA,14,...,NaN,NaN,NaN,DH,LA 58,I,0,5,0.848771,False
19234,2018122200,2300,(7:53) J.Johnson pass incomplete short left [K...,3,2,5,WAS,play_type_unknown,WAS,31,...,NaN,NaN,NaN,DH,TEN 24,I,0,5,0.848703,False
19235,2018122200,3177,(6:53) (Shotgun) B.Gabbert pass incomplete sho...,4,3,7,TEN,play_type_unknown,WAS,37,...,NaN,NaN,NaN,DH,WAS 31,I,0,5,1.227695,False
19236,2018122201,566,(5:32) (Shotgun) P.Rivers pass deep right to K...,1,3,4,LAC,play_type_unknown,LAC,49,...,NaN,NaN,NaN,OPI,LAC 13,C,27,-10,-0.720168,False
19237,2018122201,1719,(1:08) P.Rivers pass incomplete deep middle to...,2,3,1,LAC,play_type_unknown,LAC,48,...,NaN,NaN,NaN,DPI,BAL 23,I,0,15,1.336078,True
19238,2018122201,2649,(7:16) (Shotgun) L.Jackson pass incomplete sho...,3,1,10,BAL,play_type_unknown,LAC,49,...,NaN,NaN,NaN,DPI,LAC 43,I,0,9,0.550256,True

In [28]:
week1_df.head()

,time,x,y,s,a,dis,o,dir,event,nflId,displayName,jerseyNumber,position,frameId,team,gameId,playId,playDirection,route
0,2018-09-07T01:07:14.599Z,91.73,26.67,0.00,0.01,0.02,289.57,240.93,None,310.0,Matt Ryan,2.0,QB,1,away,2018090600,75,left,NaN
1,2018-09-07T01:07:14.599Z,88.89,36.47,0.01,0.01,0.01,105.63,66.66,None,79848.0,Malcolm Jenkins,27.0,SS,1,home,2018090600,75,left,NaN
2,2018-09-07T01:07:14.599Z,91.35,44.16,0.02,0.03,0.01,290.45,16.86,None,2495454.0,Julio Jones,11.0,WR,1,away,2018090600,75,left,HITCH
3,2018-09-07T01:07:14.599Z,86.31,22.01,0.09,0.42,0.01,70.12,168.91,None,2495613.0,Corey Graham,24.0,FS,1,home,2018090600,75,left,NaN
4,2018-09-07T01:07:14.599Z,90.78,36.15,0.00,0.00,0.00,257.61,193.97,None,2533040.0,Mohamed Sanu,12.0,WR,1,away,2018090600,75,left,HITCH

In [29]:
# join play data with weekly data
week1plays_df = week1_df.join(plays_df, lsuffix="_left")
week2plays_df = week2_df.join(plays_df, lsuffix="_left")
week3plays_df = week3_df.join(plays_df, lsuffix="_left")

In [30]:
week1plays_df.head(10)

,time,x,y,s,a,dis,o,dir,event,nflId,...,preSnapHomeScore,gameClock,absoluteYardlineNumber,penaltyCodes,penaltyJerseyNumbers,passResult,offensePlayResult,playResult,epa,isDefensivePI
0,2018-09-07T01:07:14.599Z,91.73,26.67,0.00,0.01,0.02,289.57,240.93,None,310.0,...,0.0,15:00:00,90.0,NaN,NaN,C,10.0,10.0,0.261827,False
1,2018-09-07T01:07:14.599Z,88.89,36.47,0.01,0.01,0.01,105.63,66.66,None,79848.0,...,0.0,13:10:00,49.0,NaN,NaN,I,0.0,0.0,-0.372360,False
2,2018-09-07T01:07:14.599Z,91.35,44.16,0.02,0.03,0.01,290.45,16.86,None,2495454.0,...,0.0,13:05:00,49.0,NaN,NaN,I,0.0,0.0,-0.702779,False
3,2018-09-07T01:07:14.599Z,86.31,22.01,0.09,0.42,0.01,70.12,168.91,None,2495613.0,...,0.0,13:01:00,49.0,NaN,NaN,C,33.0,33.0,3.047530,False
4,2018-09-07T01:07:14.599Z,90.78,36.15,0.00,0.00,0.00,257.61,193.97,None,2533040.0,...,0.0,10:59:00,11.0,NaN,NaN,I,0.0,0.0,-0.842272,False
5,2018-09-07T01:07:14.599Z,73.64,28.70,0.03,0.02,0.01,103.05,219.41,None,2534832.0,...,0.0,10:10:00,14.0,NaN,NaN,C,4.0,4.0,-0.344096,False
6,2018-09-07T01:07:14.599Z,98.25,26.63,0.01,0.01,0.00,265.88,194.51,None,2543583.0,...,0.0,09:24:00,18.0,NaN,NaN,I,0.0,0.0,-1.192208,False
7,2018-09-07T01:07:14.599Z,86.48,31.12,0.09,0.03,0.04,95.90,33.36,None,2552315.0,...,0.0,09:08:00,54.0,NaN,NaN,I,0.0,0.0,-0.429863,False
8,2018-09-07T01:07:14.599Z,82.67,20.53,0.03,0.07,0.01,81.14,174.57,None,2552689.0,...,0.0,07:01:00,46.0,NaN,NaN,C,26.0,26.0,1.879804,False
9,2018-09-07T01:07:14.599Z,84.00,43.49,0.14,0.05,0.01,108.23,110.32,None,2555383.0,...,0.0,06:19:00,20.0,NaN,NaN,C,3.0,3.0,0.045665,False

In [31]:
week1plays_df.tail(10)

,time,x,y,s,a,dis,o,dir,event,nflId,...,preSnapHomeScore,gameClock,absoluteYardlineNumber,penaltyCodes,penaltyJerseyNumbers,passResult,offensePlayResult,playResult,epa,isDefensivePI
986012,2018-09-11T05:29:39.900Z,25.02,36.59,4.65,1.28,0.47,49.06,12.98,None,2543492.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
986013,2018-09-11T05:29:39.900Z,46.48,30.70,1.43,0.84,0.14,286.98,270.58,None,2543499.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
986014,2018-09-11T05:29:39.900Z,32.43,38.52,3.36,2.34,0.35,318.15,315.18,None,2550597.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
986015,2018-09-11T05:29:39.900Z,31.66,27.20,2.24,1.38,0.23,338.10,351.64,None,2552487.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
986016,2018-09-11T05:29:39.900Z,23.66,20.13,2.63,2.49,0.27,24.32,12.77,None,2552488.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
986017,2018-09-11T05:29:39.900Z,33.68,43.14,1.96,3.79,0.22,281.35,309.70,None,2556277.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
986018,2018-09-11T05:29:39.900Z,36.02,40.21,0.81,1.52,0.09,308.07,234.06,None,2556593.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
986019,2018-09-11T05:29:39.900Z,33.02,43.81,2.63,4.57,0.27,183.83,314.39,None,2556885.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
986020,2018-09-11T05:29:39.900Z,34.13,40.86,0.15,0.72,0.02,6.17,267.87,None,2558183.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
986021,2018-09-11T05:29:39.900Z,33.29,43.92,1.81,4.24,0.20,NaN,NaN,None,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [32]:
week1plays_df.shape

(986022, 46)

In [33]:
week2plays_df.shape

(1231793, 46)

In [34]:
week3plays_df.shape

(1168345, 46)

In [35]:
for col in week1plays_df.columns:
    print(col)

time
x
y
s
a
dis
o
dir
event
nflId
displayName
jerseyNumber
position
frameId
team
gameId_left
playId_left
playDirection
route
gameId
playId
playDescription
quarter
down
yardsToGo
possessionTeam
playType
yardlineSide
yardlineNumber
offenseFormation
personnelO
defendersInTheBox
numberOfPassRushers
personnelD
typeDropback
preSnapVisitorScore
preSnapHomeScore
gameClock
absoluteYardlineNumber
penaltyCodes
penaltyJerseyNumbers
passResult
offensePlayResult
playResult
epa
isDefensivePI

In [36]:
for col in players_df.columns:
    print(col)

nflId
height
weight
birthDate
collegeName
position
displayName

In [47]:
week1plays_df.describe()

,x,y,s,a,dis,o,dir,nflId,jerseyNumber,frameId,...,yardsToGo,yardlineNumber,defendersInTheBox,numberOfPassRushers,preSnapVisitorScore,preSnapHomeScore,absoluteYardlineNumber,offensePlayResult,playResult,epa
count,986022.000000,986022.000000,986022.000000,986022.000000,986022.000000,919109.000000,919109.000000,9.191090e+05,919109.000000,986022.000000,...,19239.000000,19239.000000,19177.000000,18606.000000,18600.000000,18600.000000,18600.000000,19239.000000,19239.000000,19239.000000
mean,58.975056,26.795439,3.187303,2.012526,0.323366,179.545196,181.238304,2.366598e+06,37.763714,35.450674,...,8.923905,29.860232,6.036189,4.216543,10.758333,12.465484,59.905753,6.279380,6.469047,0.020725
std,24.935961,11.204589,2.843484,1.689410,0.307017,100.706586,102.965112,6.193264e+05,24.977470,23.654286,...,3.974216,12.444118,1.015547,0.897862,9.798115,10.552753,23.641588,10.184296,10.566605,1.580748
min,-5.980000,-11.740000,0.000000,0.000000,0.000000,0.000000,0.000000,3.060000e+02,1.000000,1.000000,...,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000,11.000000,-19.000000,-78.000000,-11.935951
25%,39.980000,19.000000,0.850000,0.740000,0.090000,89.880000,91.520000,2.533040e+06,20.000000,17.000000,...,6.000000,21.500000,6.000000,4.000000,3.000000,3.000000,40.000000,0.000000,0.000000,-0.745327
50%,59.100000,26.830000,2.790000,1.750000,0.280000,177.430000,181.410000,2.552255e+06,29.000000,33.000000,...,10.000000,30.000000,6.000000,4.000000,9.000000,10.000000,60.000000,4.000000,4.000000,-0.190540
75%,78.190000,34.710000,4.960000,2.940000,0.500000,269.840000,271.350000,2.556480e+06,53.000000,50.000000,...,10.000000,40.000000,7.000000,5.000000,17.000000,20.000000,80.000000,10.000000,11.000000,0.976822
max,128.380000,62.750000,27.370000,58.330000,7.120000,360.000000,360.000000,2.561485e+06,99.000000,172.000000,...,41.000000,50.000000,11.000000,10.000000,51.000000,54.000000,109.000000,97.000000,97.000000,8.629316

In [55]:
stats_positive = week1plays_df[week1plays_df["playResult"] > 0].describe()
stats_positive.rename(columns=lambda x: x + " positive gain", inplace=True)

stats_negative = week1plays_df[week1plays_df["playResult"] < 0].describe()
stats_negative.rename(columns=lambda x: x + " negative gain", inplace=True)

stats_zero = week1plays_df[week1plays_df["playResult"] == 0].describe()
stats_zero.rename(columns=lambda x: x + " zero gain", inplace=True)

stats_positive

,x positive gain,y positive gain,s positive gain,a positive gain,dis positive gain,o positive gain,dir positive gain,nflId positive gain,jerseyNumber positive gain,frameId positive gain,...,yardsToGo positive gain,yardlineNumber positive gain,defendersInTheBox positive gain,numberOfPassRushers positive gain,preSnapVisitorScore positive gain,preSnapHomeScore positive gain,absoluteYardlineNumber positive gain,offensePlayResult positive gain,playResult positive gain,epa positive gain
count,11255.000000,11255.000000,11255.000000,11255.000000,11255.000000,10485.000000,10485.000000,1.048500e+04,10485.000000,11255.000000,...,11255.000000,11255.000000,11230.000000,10751.000000,10747.000000,10747.000000,10747.000000,11255.000000,11255.000000,11255.000000
mean,43.259106,26.257636,2.906371,2.090614,0.294664,180.833376,190.894184,2.332362e+06,32.482022,32.512572,...,9.013416,30.067792,6.025735,4.168728,10.666884,12.453801,59.942496,11.395558,12.092848,0.838272
std,21.852199,10.589172,2.711518,1.840349,0.293433,99.693817,103.361269,6.951634e+05,22.037181,20.310387,...,4.026778,12.276179,1.013559,0.839819,9.750123,10.618347,23.345073,10.227330,10.192374,1.266095
min,-0.120000,-4.280000,0.000000,0.000000,0.000000,0.100000,0.120000,3.100000e+02,2.000000,1.000000,...,1.000000,1.000000,2.000000,0.000000,0.000000,0.000000,11.000000,-15.000000,1.000000,-5.355284
25%,23.970000,19.120000,0.680000,0.700000,0.070000,89.250000,97.290000,2.533040e+06,18.000000,16.000000,...,7.000000,22.000000,6.000000,4.000000,3.000000,3.000000,41.000000,5.000000,6.000000,-0.072835
50%,45.520000,25.430000,2.440000,1.780000,0.240000,182.480000,200.340000,2.552315e+06,24.000000,31.000000,...,10.000000,30.000000,6.000000,4.000000,9.000000,10.000000,60.000000,9.000000,9.000000,0.761681
75%,56.155000,33.470000,4.570000,3.100000,0.460000,271.390000,276.590000,2.555383e+06,44.000000,46.000000,...,10.000000,40.000000,7.000000,4.000000,17.000000,20.000000,80.000000,15.000000,15.000000,1.598640
max,98.580000,55.090000,25.340000,30.650000,5.120000,359.930000,359.980000,2.560995e+06,88.000000,100.000000,...,41.000000,50.000000,11.000000,9.000000,51.000000,54.000000,109.000000,97.000000,97.000000,8.629316

In [56]:
stats_negative

,x negative gain,y negative gain,s negative gain,a negative gain,dis negative gain,o negative gain,dir negative gain,nflId negative gain,jerseyNumber negative gain,frameId negative gain,...,yardsToGo negative gain,yardlineNumber negative gain,defendersInTheBox negative gain,numberOfPassRushers negative gain,preSnapVisitorScore negative gain,preSnapHomeScore negative gain,absoluteYardlineNumber negative gain,offensePlayResult negative gain,playResult negative gain,epa negative gain
count,1665.000000,1665.000000,1665.000000,1665.000000,1665.000000,1546.000000,1546.000000,1.546000e+03,1546.000000,1665.000000,...,1665.000000,1665.000000,1662.000000,1583.000000,1583.000000,1583.000000,1583.000000,1665.000000,1665.000000,1665.000000
mean,43.197922,25.877652,2.971123,2.054066,0.299994,177.539366,190.871895,2.345465e+06,32.134541,33.075075,...,9.010210,30.480480,6.030686,4.429564,10.747947,12.544536,59.718256,-4.625826,-6.995195,-1.525961
std,22.885935,10.784281,2.643144,1.685611,0.297030,98.429366,103.868544,6.755232e+05,21.616068,20.420955,...,4.116602,12.121967,0.978835,0.878848,9.570037,10.431239,22.941584,6.646820,5.833320,1.281290
min,1.030000,-0.200000,0.000000,0.000000,0.000000,0.340000,0.010000,3.100000e+02,2.000000,1.000000,...,1.000000,1.000000,2.000000,0.000000,0.000000,0.000000,11.000000,-19.000000,-78.000000,-10.951801
25%,22.580000,18.630000,0.800000,0.750000,0.080000,89.112500,94.577500,2.533040e+06,18.000000,16.000000,...,6.000000,23.000000,6.000000,4.000000,3.000000,3.000000,40.000000,-8.000000,-9.000000,-1.926385
50%,45.340000,25.370000,2.590000,1.800000,0.260000,172.500000,203.400000,2.552315e+06,24.000000,32.000000,...,10.000000,31.000000,6.000000,4.000000,9.000000,10.000000,60.000000,-6.000000,-7.000000,-1.170036
75%,57.100000,33.430000,4.550000,3.100000,0.450000,268.720000,276.635000,2.555383e+06,44.000000,47.000000,...,10.000000,40.000000,7.000000,5.000000,17.000000,20.000000,79.000000,-2.000000,-4.000000,-0.748868
max,98.570000,55.100000,23.060000,14.890000,5.410000,359.620000,359.390000,2.560995e+06,88.000000,100.000000,...,38.000000,50.000000,11.000000,10.000000,45.000000,52.000000,109.000000,75.000000,-1.000000,0.420482

In [57]:
stats_zero

,x zero gain,y zero gain,s zero gain,a zero gain,dis zero gain,o zero gain,dir zero gain,nflId zero gain,jerseyNumber zero gain,frameId zero gain,...,yardsToGo zero gain,yardlineNumber zero gain,defendersInTheBox zero gain,numberOfPassRushers zero gain,preSnapVisitorScore zero gain,preSnapHomeScore zero gain,absoluteYardlineNumber zero gain,offensePlayResult zero gain,playResult zero gain,epa zero gain
count,6319.000000,6319.000000,6319.00000,6319.000000,6319.000000,5858.000000,5858.000000,5.858000e+03,5858.000000,6319.000000,...,6319.000000,6319.000000,6285.000000,6272.000000,6270.000000,6270.000000,6270.000000,6319.000000,6319.0,6319.000000
mean,44.209832,26.611369,2.95793,2.071313,0.301008,183.239227,190.300603,2.326974e+06,32.436497,32.633486,...,8.741731,29.327109,6.056325,4.244739,10.917703,12.465550,59.890112,0.040196,0.0,-1.027900
std,22.131612,10.486570,2.85876,1.770003,0.321056,99.543833,104.779082,7.033052e+05,22.202765,20.746221,...,3.833726,12.803201,1.028405,0.985732,9.935632,10.471742,24.314652,0.983062,0.0,1.183209
min,-0.720000,-4.820000,0.00000,0.000000,0.000000,0.010000,0.030000,3.100000e+02,2.000000,1.000000,...,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000,11.000000,-6.000000,0.0,-11.935951
25%,24.775000,19.845000,0.66000,0.720000,0.070000,90.610000,94.252500,2.533040e+06,18.000000,15.000000,...,6.000000,20.000000,6.000000,4.000000,3.000000,3.000000,40.000000,0.000000,0.0,-1.216619
50%,46.450000,26.020000,2.46000,1.740000,0.240000,190.055000,200.300000,2.552301e+06,24.000000,31.000000,...,10.000000,30.000000,6.000000,4.000000,9.000000,10.000000,60.000000,0.000000,0.0,-0.645578
75%,57.180000,34.170000,4.59000,3.060000,0.460000,271.685000,277.815000,2.555383e+06,44.000000,47.000000,...,10.000000,40.000000,7.000000,5.000000,17.000000,20.000000,80.000000,0.000000,0.0,-0.397819
max,98.580000,54.920000,25.64000,15.990000,5.380000,359.950000,359.910000,2.560995e+06,88.000000,100.000000,...,30.000000,50.000000,11.000000,8.000000,51.000000,54.000000,109.000000,39.000000,0.0,2.999528